stages:
    - build

buildAssets:
    # 指定需要使用哪个镜像来构建，默认node-gulp，带node/npm/gulp/git
    image: node-gulp
    stage: build
    # 构建脚本，注意指定内网registry，gulp仍然可用
    # 注意：不需要文件打包清理相关命令
    script:
        - npm ci node-sass --sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
        - node_modules/.bin/webpack --config=webpack.prod.config.js
    # 最后打包生成的文件包，不需要手工打包
    artifacts:
        # paths中的所有文件会被打包，相对于根目录
        paths:
            - static/dist
            - server/views
        # 文件包过期时间，一般设2周
        expire_in: 2 weeks
